name: CD | DockerHub Deploy

on:
  push:
    branches:
      - "main"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: false
        default: "dev"

jobs:
  docker-build:
    runs-on: [self-hosted, Linux, X64]  # Corrected to include the label directly in runs-on

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag) || 'dev' }}

  docker-test:
    needs: [docker-build]
    runs-on: [self-hosted, Linux, X64]  # Corrected to include the label directly in runs-on

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests on Docker Image
        if: github.event_name != 'release'
        id: run-tests
        uses: direlines/runpod-test-runner@v1.7
        with:
          image-tag: ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag) || 'dev' }}
          runpod-api-key: ${{ secrets.RUNPOD_API_KEY }}
          request-timeout: 600

      - name: Verify Tests
        env:
          TOTAL_TESTS: ${{ steps.run-tests.outputs.total-tests }}
          SUCCESSFUL_TESTS: ${{ steps.run-tests.outputs.succeeded }}
          RESULTS: ${{ steps.run-tests.outputs.results }}
        run: |
          echo "Total tests: $TOTAL_TESTS"
          echo "Successful tests: $SUCCESSFUL_TESTS"
          echo "Full results: $RESULTS"
          if [ "$TOTAL_TESTS" != "$SUCCESSFUL_TESTS" ]; then
              exit 1
          fi